export function motionHtml() {
  return '<div class="motionGrid"></div><div class="mouseGlow"></div>';
}

export function motionCss() {
  return `
:root{--mouse-x:50vw;--mouse-y:50vh}.motionGrid{position:fixed;inset:-20%;pointer-events:none;z-index:0;opacity:.16;background:linear-gradient(90deg,transparent 0 96%,rgba(255,255,255,.14) 97% 100%),linear-gradient(0deg,transparent 0 96%,rgba(255,255,255,.1) 97% 100%);background-size:72px 72px;transform:perspective(900px) rotateX(62deg) translateY(-22%);animation:gridDrift 22s linear infinite}.mouseGlow{position:fixed;left:0;top:0;width:520px;height:520px;border-radius:999px;pointer-events:none;z-index:1;background:radial-gradient(circle,var(--glow),transparent 65%);transform:translate(calc(var(--mouse-x) - 260px),calc(var(--mouse-y) - 260px));filter:blur(6px);opacity:.72}.reveal{opacity:0;transform:translateY(30px) scale(.98);filter:blur(10px);transition:opacity .8s cubic-bezier(.2,.8,.2,1),transform .8s cubic-bezier(.2,.8,.2,1),filter .8s ease;transition-delay:calc(var(--stagger,0) * 85ms)}.reveal.visible{opacity:1;transform:none;filter:blur(0)}.animatedBorder{position:relative;overflow:hidden}.animatedBorder:after{content:'';position:absolute;inset:0;border-radius:inherit;border:1px solid color-mix(in srgb,var(--accent) 55%,transparent);opacity:.36;box-shadow:0 0 32px var(--glow);pointer-events:none;animation:borderPulse 3.8s ease-in-out infinite}.parallaxLayer{will-change:transform}.floatAsset{animation:floatSoft 7s ease-in-out infinite}.magnetic{will-change:transform}.sectionTransition{position:relative}.sectionTransition:before{content:'';position:absolute;left:5vw;right:5vw;top:0;height:1px;background:linear-gradient(90deg,transparent,var(--accent),transparent);opacity:.38}@keyframes gridDrift{to{transform:perspective(900px) rotateX(62deg) translateY(-22%) translateX(72px)}}@keyframes borderPulse{0%,100%{opacity:.18}50%{opacity:.58}}@keyframes floatSoft{0%,100%{transform:translateY(0)}50%{transform:translateY(-12px)}}@media(max-width:1000px){.mouseGlow{display:none}}@media(prefers-reduced-motion:reduce){*,*:before,*:after{animation:none!important;transition:none!important;scroll-behavior:auto!important}.mouseGlow,.motionGrid{display:none}}
`;
}

export function motionJs() {
  return `
const root=document.documentElement;document.addEventListener('mousemove',(event)=>{root.style.setProperty('--mouse-x',event.clientX+'px');root.style.setProperty('--mouse-y',event.clientY+'px');});document.querySelectorAll('.magnetic').forEach((button)=>{button.addEventListener('mousemove',(event)=>{const rect=button.getBoundingClientRect();const x=(event.clientX-rect.left-rect.width/2)*.16;const y=(event.clientY-rect.top-rect.height/2)*.16;button.style.transform='translate('+x+'px,'+y+'px)';});button.addEventListener('mouseleave',()=>{button.style.transform='';});});function runParallax(){document.querySelectorAll('.parallaxLayer').forEach((el)=>{const speed=parseFloat(el.dataset.parallax||'.08');const rect=el.getBoundingClientRect();const offset=(rect.top-window.innerHeight/2)*speed;el.style.transform='translate3d(0,'+(-offset)+'px,0)';});requestAnimationFrame(runParallax);}requestAnimationFrame(runParallax);document.querySelectorAll('.reveal').forEach((el,index)=>{if(!el.style.getPropertyValue('--stagger'))el.style.setProperty('--stagger',String(index%6));});
`;
}
