import React from 'react';
import AppLogo from '@/components/ui/AppLogo';
import { Cpu, Zap, Globe, Code2 } from 'lucide-react';
import Icon from '@/components/ui/AppIcon';


const features = [
  { id: 'feat-ai', icon: Cpu, title: 'AI-Powered Generation', description: 'Describe your site in plain English — AI writes every line of code' },
  { id: 'feat-live', icon: Zap, title: 'Instant Live Preview', description: 'See your website render in real-time as AI generates the code' },
  { id: 'feat-deploy', icon: Globe, title: 'Deploy-Ready Output', description: 'Get clean, production-ready HTML, CSS and JavaScript every time' },
  { id: 'feat-editor', icon: Code2, title: 'Monaco Code Editor', description: 'Edit generated code directly with full syntax highlighting and autocomplete' },
];

const floatingCards = [
  { id: 'fc-1', label: 'SaaS Landing', color: '#6EE7B7', delay: '0s' },
  { id: 'fc-2', label: 'Portfolio', color: '#818CF8', delay: '0.4s' },
  { id: 'fc-3', label: 'E-commerce', color: '#F59E0B', delay: '0.8s' },
];

export default function AuthBrandPanel() {
  return (
    <div className="hidden lg:flex flex-col w-1/2 xl:w-[55%] relative overflow-hidden"
      style={{ background: 'linear-gradient(135deg, #0A0A0F 0%, #0F0F1A 50%, #0A0A0F 100%)' }}>
      {/* Background grid */}
      <div className="absolute inset-0 bg-grid opacity-60" />
      {/* Glow blobs */}
      <div className="absolute top-1/4 left-1/4 w-64 h-64 rounded-full blur-3xl opacity-10"
        style={{ background: 'var(--primary)' }} />
      <div className="absolute bottom-1/3 right-1/4 w-48 h-48 rounded-full blur-3xl opacity-10"
        style={{ background: 'var(--accent)' }} />
      {/* Content */}
      <div className="relative z-10 flex flex-col h-full p-10 xl:p-14">
        {/* Logo */}
        <div className="flex items-center gap-3">
          <AppLogo size={36} />
          <span className="text-xl font-semibold tracking-tight text-gradient-primary">BuildAI</span>
        </div>

        {/* Hero text */}
        <div className="mt-16 mb-10">
          <h1 className="text-4xl xl:text-5xl font-bold text-foreground leading-tight mb-4">
            Build websites with<br />
            <span className="text-gradient-primary">AI in seconds</span>
          </h1>
          <p className="text-base text-muted-foreground leading-relaxed max-w-md">
            Describe your website. Watch AI generate it. Edit with Monaco. Deploy instantly. No coding required.
          </p>
        </div>

        {/* Floating preview cards */}
        <div className="flex gap-3 mb-10">
          {floatingCards?.map((card) => (
            <div
              key={card?.id}
              className="glass px-4 py-3 rounded-xl animate-pulse-slow"
              style={{ animationDelay: card?.delay }}
            >
              <div className="w-2 h-2 rounded-full mb-2" style={{ background: card?.color }} />
              <p className="text-xs font-medium text-foreground">{card?.label}</p>
              <p className="text-xs text-muted-foreground">Generated by AI</p>
            </div>
          ))}
        </div>

        {/* Feature list */}
        <div className="space-y-4 mt-auto">
          {features?.map((feature) => {
            const Icon = feature?.icon;
            return (
              <div key={feature?.id} className="flex items-start gap-3">
                <div className="w-8 h-8 rounded-lg bg-primary/10 flex items-center justify-center flex-shrink-0 mt-0.5">
                  <Icon size={15} className="text-primary" />
                </div>
                <div>
                  <p className="text-sm font-medium text-foreground">{feature?.title}</p>
                  <p className="text-xs text-muted-foreground mt-0.5">{feature?.description}</p>
                </div>
              </div>
            );
          })}
        </div>

        {/* Footer note */}
        <p className="text-xs text-muted-foreground mt-8">
          Trusted by 4,200+ developers and founders worldwide
        </p>
      </div>
    </div>
  );
}